version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
    labels:
      - 'npm dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
